### PR TITLE
Clean up nav and footer

### PR DESCRIPTION
**Pull request by KevinCawley**
This removed the news and mission statement 
**Description**

The News and Mission were commented out in the config.yaml file. 

However, for some reason that I cannot diagnose, the home page is a 404 error, but all the other pages work so far. Help would be appreciated. 
**Motivation and context**

**How has this been tested?**
- [ ] Testing pipeline.
- [ ] Other. 

**Examples**

**Type of change**

- [ ] Bug fix. 
- [ ] New feature. 
- [ ] Breaking change. 
- [ ] None of the above. 

**Checklist**

- [ ] My change requires a change to the documentation.
    - [ ] I have updated the documentation accordingly.
    - [ ] (optional) I have built the documentation on my fork following [the instructions](https://tardis-sn.github.io/tardis/development/documentation_preview.html).
- [ ] I have assigned and requested two reviewers for this pull request.

### CODE REVIEW

**Comment by KevinCawley** [comment]
https://kevincawley.github.io/tardis-sn.github.io/branch/clean_up_nav_and_footer/

Base URL, leads to 404 error. 

Any other URL on the branch, such as 
https://kevincawley.github.io/tardis-sn.github.io/branch/clean_up_nav_and_footer/credits/
works.

**Comment by KevinCawley** [comment]
This has been fixed, I believe it was a GitHub issue that it wasn't all built and it just took a while.

**Review by DhruvSondhi — APPROVED** [review]
Working as intended. Looks good to me :)

**Review by jaladh-singhal — APPROVED** [review]
Easy peasy! :)

**Pull request merged**
