### PR TITLE
Modify links markdown

### LINKED ISSUE #13: Better way to add links opening in new tabs in markdown
Convert all external links in markdown files from `<a target="_blank">..</a>` to markdown native syntax that's cleaner - `[text](url)`

There already exists ways to tell Hugo to render external links as `target="_blank"` links when preparing html from markdown:
- https://discourse.gohugo.io/t/how-to-target--blank-in-md/524/12
- Using JS: https://stackoverflow.com/a/4425214/8252556

### PR DESCRIPTION
**Pull request by rohithvarma3000**
**Description**

Modify the anchor tags to link markdown and change the JS code to modify the target. Fixes #13 

**Motivation and context**

Allows us to use the links markdown in the markdown files and set `target="_blank"` for external links.

**How has this been tested?**
- [ ] Testing pipeline.
- [x] Other. 
Manual

**Type of change**

- [x] Bug fix. 
- [ ] New feature. 
- [ ] Breaking change. 
- [ ] None of the above. 

**Checklist**

- [ ] My change requires a change to the documentation.
    - [ ] I have updated the documentation accordingly.
    - [ ] (optional) I have built the documentation on my fork following [the instructions](https://tardis-sn.github.io/tardis/contributing/development/documentation_guidelines.html#sharing-the-built-documentation-in-your-pr-documentation-preview).
- [x] I have assigned and requested two reviewers for this pull request.

### CODE REVIEW

**Comment by rohithvarma3000** [comment]
@jaladh-singhal Please review the PR.

**Comment by jaladh-singhal** [comment]
@rohithvarma3000 thanks for this - can you please share the built website on your fork?

**Comment by rohithvarma3000** [comment]
@jaladh-singhal I have built the website and pushed it to the branch `link-md-demo` in my fork.

**Comment by KevinCawley** [comment]
I wasn't able to find it at https://rohithvarma3000.github.io/tardis-sn.github.io/branch/link-md-demo/ or https://rohithvarma3000.github.io/tardis-sn.github.io/branch/link-md/

**Comment by rohithvarma3000** [comment]
I am sorry. Since this was the first time working on this repository, I did not know the presence of the workflows. https://rohithvarma3000.github.io/tardis-sn.github.io/branch/link-md-demo/ works now. Please have a look into it

**Pull request closed without merging**
