### PR TITLE
Move GSoC Page To The Main TARDIS Website

### PR DESCRIPTION
**Pull request by atharva-2001**
### :pencil: Description

This pull request tries to move the GSoC website contents over to the main TARDIS Website. I believe this would help students have easier access to TARDIS documentation and other web pages and might help us attract more students.

This pull request is branched off of the branch in this pull request: https://github.com/tardis-sn/tardis-sn.github.io/pull/37 and it would be great if that is merged before.

Preview: https://atharva-2001.github.io/tardis-sn.github.io/branch/move_gsoc/

### :pushpin: Resources

Examples, notebooks, and links to useful references.

### :vertical_traffic_light: Testing

How did you test these changes?

- [ ] Testing pipeline
- [ ] Other method (describe)
- [ ] My changes can't be tested (explain why)

### :ballot_box_with_check: Checklist

- [ ] I requested two reviewers for this pull request
- [ ] I updated the documentation according to my changes
- [ ] I built the documentation by applying the `build_docs` label

> **Note:** If you are not allowed to perform any of these actions, ping (@) a contributor.

### CODE REVIEW

**Comment by andrewfullard** [comment]
Preview shows "GSoC New" and "GSoC". The New link is broken. The other one goes to the current GSoC site.

**Comment by andrewfullard** [comment]
I like the new page. Would be nice to have the GSoC logo on there if possible, and it should just replace the old site with content from that old site merged in.

**Comment by andrewfullard** [comment]
Looking good. You should remove the link to the old site now.

**Comment by atharva-2001** [comment]
> Looking good. You should remove the link to the old site now and make sure all the content has been transferred.

Done!

**Comment by andrewfullard** [comment]
Looks good. Would like a review from @wkerzendorf or similar. Maybe want to wait to push until we have some ideas up?

**Review by andrewfullard — APPROVED** [review]

**Comment by marxwillia** [comment]
Participation Expectations page has a mistake in it: <<email_kerzendorf>> appears in the Resolving Problems section.

**Comment by atharva-2001** [comment]
> Participation Expectations page has a mistake in it: <<email_kerzendorf>> appears in the Resolving Problems section.

@wkerzendorf, should I replace <<email_kerzendorf>> by this email: tardis.supernova.code@gmail.com (mentioned [here](https://tardis-sn.github.io/code_of_conduct/) for voilations of code of conduct)?

**Comment by atharva-2001** [comment]
> Participation Expectations page has a mistake in it: <<email_kerzendorf>> appears in the Resolving Problems section.

Fixed in [1996128](https://github.com/tardis-sn/tardis-sn.github.io/pull/38/commits/19961282b97d1f331f9291ba5d451e210fd7cc48).

**Pull request merged**
